In [1]:
!pip install mlflow --quiet

import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing
import pandas as pd

# Cargar dataset
data = fetch_california_housing(as_frame=True)
X = data.data
y = data.target

# Dividir en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 kB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 56.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 54.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 34.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.4/208.4 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.2/131.2 kB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 838.5/838.5 kB 23.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 8.8 MB/s eta 0:00:00

In [2]:
mlflow.set_experiment("rf_experimento_california")

2026/04/10 03:44:22 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/04/10 03:44:23 INFO mlflow.store.db.utils: Updating database tables
2026/04/10 03:44:25 INFO mlflow.tracking.fluent: Experiment with name 'rf_experimento_california' does not exist. Creating a new experiment.

<Experiment: artifact_location='/content/mlruns/1', creation_time=1775792665522, experiment_id='1', last_update_time=1775792665522, lifecycle_stage='active', name='rf_experimento_california', tags={}, trace_location=None, workspace='default'>

In [3]:
params_grid = [
{"n_estimators": 50, "max_depth": 5},
{"n_estimators": 100, "max_depth": 5},
{"n_estimators": 100, "max_depth": 10},
{"n_estimators": 200, "max_depth": 10},
{"n_estimators": 200, "max_depth": None},
{"n_estimators": 300, "max_depth": None},
]

In [4]:
for params in params_grid:
  with mlflow.start_run(run_name=f"rf_ne{params['n_estimators']}_md{params['max_depth']}"):

    # Registrar parámetros
    mlflow.log_param("n_estimators", params["n_estimators"])
    mlflow.log_param("max_depth", params["max_depth"])

    # Entrenar modelo
    model = RandomForestRegressor(
    n_estimators=params["n_estimators"],
    max_depth=params["max_depth"],
    random_state=42
    )
    model.fit(X_train, y_train)

    # Registrar métrica
    r2 = model.score(X_test, y_test)
    mlflow.log_metric("r2", r2)

    # Guardar modelo entrenado
    mlflow.sklearn.log_model(model, "model_rf")

  print(f"Run: {params} → R² = {r2:.4f}")

2026/04/10 03:45:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/10 03:45:06 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Run: {'n_estimators': 50, 'max_depth': 5} → R² = 0.6469

2026/04/10 03:45:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/10 03:45:16 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Run: {'n_estimators': 100, 'max_depth': 5} → R² = 0.6468

2026/04/10 03:45:28 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/10 03:45:28 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Run: {'n_estimators': 100, 'max_depth': 10} → R² = 0.7737

2026/04/10 03:45:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/10 03:45:50 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Run: {'n_estimators': 200, 'max_depth': 10} → R² = 0.7748

2026/04/10 03:46:21 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/10 03:46:21 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Run: {'n_estimators': 200, 'max_depth': None} → R² = 0.8062

2026/04/10 03:47:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/10 03:47:10 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Run: {'n_estimators': 300, 'max_depth': None} → R² = 0.8066

In [5]:
exp = mlflow.get_experiment_by_name("rf_experimento_california")
experiment_id = exp.experiment_id
df_runs = mlflow.search_runs(experiment_ids=[experiment_id])
df_summary = df_runs[
["run_id", "params.n_estimators", "params.max_depth", "metrics.r2"]
].sort_values("metrics.r2", ascending=False)

df_summary

,run_id,params.n_estimators,params.max_depth,metrics.r2
0,c2ff46548d3f43b1a847859432f0a3bf,300,None,0.806600
1,97ab1508cb21445da70c915d2d23f045,200,None,0.806186
2,f0494ec01478446cb93aab0dd77c1705,200,10,0.774774
3,a1cb2de3acc94f818542a162428f719d,100,10,0.773740
5,cd9f506ad57a4dd2ba98a07869045d31,50,5,0.646870
4,2807983f21af40e4b8781c724627dd79,100,5,0.646831

In [7]:
best_run = df_summary.iloc[0]
best_run_id = best_run.run_id
best_run

run_id                 c2ff46548d3f43b1a847859432f0a3bf
params.n_estimators                                 300
params.max_depth                                   None
metrics.r2                                       0.8066
Name: 0, dtype: object

In [8]:
model_uri = f"runs:/{best_run_id}/model_rf"
best_model = mlflow.sklearn.load_model(model_uri)
# Realizar predicciones de prueba
best_model.predict(X_test[:5])

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

array([0.49249333, 0.73544   , 4.87372677, 2.52624   , 2.30335   ])